apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Kompose\kompose.exe convert -f docker-compose-merged.yml -o ./k8s-files/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: catalogdb
  name: catalogdb
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: catalogdb
