apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Kompose\kompose.exe convert -f docker-compose-merged.yml -o ./k8s-files/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: discount-grpc
  name: discount-grpc
spec:
  ports:
    - name: "6002"
      port: 6002
      targetPort: 80
  selector:
    io.kompose.service: discount-grpc
