apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Kompose\kompose.exe convert -f docker-compose-merged.yml -o ./k8s-files/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ordering-api
  name: ordering-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ordering-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Kompose\kompose.exe convert -f docker-compose-merged.yml -o ./k8s-files/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ordering-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTPS_PORTS
              value: "443"
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: ConnectionStrings__Database
              value: Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
            - name: FeatureManagement__OrderFullfilment
              value: "false"
            - name: MessageBroker__Host
              value: amqp://ecommerce-mq:5672
            - name: MessageBroker__Password
              value: guest
            - name: MessageBroker__UserName
              value: guest
          image: truong642003/orderingapi
          name: ordering-api
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /home/app/.aspnet/https
              name: ordering-api-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: ordering-api-cm1
          name: ordering-api-cm1
