apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Kompose\kompose.exe convert -f docker-compose-merged.yml -o ./k8s-files/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ordering-api
  name: ordering-api
spec:
  ports:
    - name: "6003"
      port: 6003
      targetPort: 80
  selector:
    io.kompose.service: ordering-api
