apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Kompose\kompose.exe convert -f docker-compose-merged.yml -o ./k8s-files/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: orderdb
  name: orderdb
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: orderdb
