apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: postgres-basket
  name: postgres-basket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
