apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Kompose\kompose.exe convert -f docker-compose-merged.yml -o ./k8s-files/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: shopping-web
  name: shopping-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shopping-web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Kompose\kompose.exe convert -f docker-compose-merged.yml -o ./k8s-files/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: shopping-web
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTPS_PORTS
              value: "443"
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: ApiSettings__GatewayAddress
              value: http://yarpapigateway:80
          image: truong642003/shoppingweb
          name: shopping-web
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /home/app/.aspnet/https
              name: shopping-web-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: shopping-web-cm1
          name: shopping-web-cm1
